# Generated by Django 3.2.18 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive_app', '0002_auto_20241015_1524'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(
                fields=['is_enabled', 'start_date', 'end_date'],
                name='assets_active_window_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(
                fields=['is_enabled', 'play_order'],
                name='assets_enabled_order_idx',
            ),
        ),
    ]
